version: 3.3.{build}
configuration: Release
platform: x86
before_build:
  - cmd: nuget restore shadowsocks-windows.sln
build:
  verbosity: minimal
test:
  off
after_build:
  - ps: $root = Resolve-Path .\shadowsocks-csharp\bin\x86; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }
